name: Firmware CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build, Test and Lint Firmware
    defaults:
        run:
            working-directory: ./firmware/bt-solar-monitor
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v3 
    - name: Install protoc
      run: | 
        sudo apt-get install -y protobuf-compiler
        protoc --version 
    - name: Setup .env from .env.development
      run: cp .env.development .env
    - name: Build, Test, Lint
      run: just ci
